version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=mercedesdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5434:5432" # Verwenden eines nicht-standard Ports

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass
      - DATABASE_NAME=mercedesdb

volumes:
  db-data:
    driver: local
